export const CHECK_AUTH = 'checkAuth'
export const FETCH_SCRAP = 'fetchScrap'
export const FETCH_SCRAPS = 'fetchScraps'
export const DELETE_SCRAP = 'deleteScrap'
export const CREATE_SCRAP = 'createScrap'
export const UPDATE_SCRAP = 'updateScrap'
export const FETCH_AUTHORS = 'fetchAuthors'
export const DELETE_AUTHOR = 'deleteAuthor'
export const CREATE_AUTHOR = 'createAuthor'
export const UPDATE_AUTHOR = 'updateAuthor'
export const FETCH_VOLUNTEERS = 'fetchVolunteer'
export const DELETE_VOLUNTEER = 'deleteVolunteer'
export const CREATE_VOLUNTEER = 'createVolunteer'
export const UPDATE_VOLUNTEER = 'updateVolunteer'

// will be obsoleted
export const FETCH_TOPICS = 'fetchTopics'
