export const SET_SCRAP = 'setScrap'
export const ADD_SCRAP = 'addScrap'
export const REMOVE_SCRAP = 'removeScrap'
export const FETCH_SCRAPS_END = 'setScraps'
export const FETCH_START = 'setLoading'
export const FETCH_AUTHORS_END = 'setAuthors'
export const SET_AUTHOR = 'setAuthor'
export const ADD_AUTHOR = 'addAuthor'
export const REMOVE_AUTHOR = 'removeAuthor'
export const SET_VOLUNTEER = 'setVolunteer'
export const ADD_VOLUNTEER = 'addVolunteer'
export const REMOVE_VOLUNTEER = 'removeVolunteer'
export const FETCH_VOLUNTEERS_END = 'setVolunteers'
export const SET_AUTH = 'setAuth'

// will be obsoleted
export const SET_TOPIC = 'setTopic'
export const FETCH_TOPICS_END = 'setTopics'
